### PR TITLE
Change available links in message form

### PR DESCRIPTION
**Pull request by gwensmu**
* Coach may select modules from the set
  of tasks currently assigned to the group
  to include in a message to a participant

[#84857732]

### CODE REVIEW

**Comment by michaelwehrley** [comment]
@gwensmu Just checking in on this.  Did you decided to an/or were you able to create any specs?  Thanks.

**Comment by gwensmu** [comment]
@michaelwehrley working on another story right now, but -- the specs that are there are a bit fudged, in that they don't test an actual link, they test placeholder text in the message. i'd want to amend the current specs for the form to test the link generation but that's a bigger task testing more than just this change. thoughts?

**Comment by michaelwehrley** [comment]
@gwensmu If I remember correctly, I thought you made a good point about stopping testing scope creep and instead just write a test that would test that we only see ```titles``` that are now part of assigned tasks and a check to make sure that ```titles``` that are not assigned are not visible.

**Comment by gwensmu** [comment]
@michaelwehrley sure i'll just write a spec for the helper then.

**Comment by michaelwehrley** [comment]
@gwensmu Thanks, I think that would be helpful.

**Comment by gwensmu** [comment]
@michaelwehrley updated specs, @ericcf sorry for not following commit message format, was an accident

**Comment by ericcf** [comment]
@gwensmu no worries. @michaelwehrley I'll let you make the call on merging this.

**Comment by michaelwehrley** [comment]
@gwensmu Instead of me being Mr. Bossy Pants, I figured, I would try to help out.  You can take a look at the commit: https://github.com/cbitstech/think_feel_do_engine/commit/b6aaddcbeb56300a460d5d8580d8b7d9470e0211 and the merge.  Thanks!

**Pull request merged**
