### PR TITLE
Add timecop method to start at beginning of minute

### PR DESCRIPTION
**Pull request by cbrenner04**
[Finish #88466220]

### CODE REVIEW

**Comment by cbrenner04** [comment]
@ericcf this recent failure is in the "implements #3 Reshape" test within thought_tracker_spec.rb. It looks like it has to do with the ```page.execute_script("$('#thought_act_as_if').val('I would act on being superman!')")``` because the failure is on occurring on ```expect(page).to have_text("I would act on being superman!")```

**Comment by cbrenner04** [comment]
hoping I solved it - @ericcf I updated the script ```page.execute_script("$('#thought_act_as_if').val('I would act on being superman!')")``` to ```fill_in "thought[act_as_if]", with: "I would act on being superman!"```. This worked locally. Fingers crossed

**Comment by cbrenner04** [comment]
YES!!! Someone review and merge please!

**Comment by ericcf** [comment]
Merging!

**Pull request merged**
