### PR TITLE
Test for Timeout

### PR DESCRIPTION
**Pull request by michaelwehrley**
* Check for the name of the participant first.

### CODE REVIEW

**Comment by eschlange** [comment]
@michaelwehrley Wasn't this causing timeouts earlier today?

**Comment by michaelwehrley** [comment]
@eschlange I was just so darn perplexed I had to try for a moment.  In the test, instead I waited for content - not just css to visible.  I am not sure if we want to proceed this way given the work you put in, but I thought it was worth taking another stab.  Thanks!

**Comment by eschlange** [comment]
Ah ok, maybe you can cycle the build a few more times to ensure that it doesn't fail, before we merge with master.

**Comment by ericcf** [comment]
@eschlange @michaelwehrley can this branch be deleted?

**Pull request closed without merging**
