### PR TITLE
Implement view membership helper in patient dahsboard

### PR DESCRIPTION
**Pull request by Tag0Mag0**
* Update inactive status view logic for relative membership

[Finishes #88267970]

### CODE REVIEW

**Comment by ericcf** [comment]
@Tag0Mag0 do any specs need updating, or is this good to go?

**Comment by Tag0Mag0** [comment]
@ericcf There are multiple specs that check the status and membership dates that didn't need to be updated. I suppose we could check whether the helper is returning that specific membership rather than some other. What do you think?

**Comment by ericcf** [comment]
I think this is reasonable. We need a review of our specs anyway, so let's handle it then.

**Comment by ericcf** [comment]
Will update the pull request in a couple of minutes.

**Comment by ericcf** [comment]
Merged. Closing.

**Pull request closed without merging**
