### PR TITLE
Gs 88754966

### PR DESCRIPTION
**Pull request by michaelwehrley**
Breakup Activity Content Provider Specs

* Each activity provider spec has their own feature test.
* Deleted original activity_spec.
* Branch has not been recently rebased

[Finishes: #88754966]

### CODE REVIEW

**Comment by eschlange** [comment]
Looks good.

**Comment by gwensmu** [comment]
working on trying to resolve that annoying update button spec before merging into master

**Comment by gwensmu** [comment]
build 257 passed so i am marking this as delivered in pivotal

**Comment by gwensmu** [comment]
correction, marked finished

**Comment by michaelwehrley** [comment]
@eschlange @gwensmu Do we have to rebase this in order to allow for a pull request?

**Comment by eschlange** [comment]
A rebase or merge should do the trick. Github is detecting merge conflicts, so there needs to be a manual conflict resolution before we are able to automatically merge in the pull request through Github.

**Comment by cbrenner04** [comment]
this will be replaced by a new merge request by gwen. will be left open until that pull request is completed.

**Comment by cbrenner04** [comment]
Closing because this was handled with another pull request: #65

**Comment by ericcf** [comment]
Ok to delete this branch?

**Comment by gwensmu** [comment]
Believe so!

**Pull request closed without merging**
