### PR TITLE
Add logic to check for no completed activities

### PR DESCRIPTION
**Pull request by gwensmu**
* Completion score only calculates a value if
  scheduled activities have been complted.
* Otherwise simply displays 0
* Fixes a division by zero error.

[#88803632]

### CODE REVIEW

**Comment by ericcf** [comment]
@gwensmu is there a spec that fails when the completed activities count == 0?

**Comment by gwensmu** [comment]
@ericcf no, i don't know how i would write a spec that fails since the view logic now catches that case.

**Comment by gwensmu** [comment]
@ericcf do you mean, a spec that passes even when completed activities count == 0?

**Comment by gwensmu** [comment]
@eschlange just made the related point in an unrelated convo that this kind of logic shouldn't be in the view - i can do the calculation in the model, and just reference it in the view -- dunno if that refactoring makes sense in the context of this bug fix @ericcf

**Comment by ericcf** [comment]
@gwensmu specs should be written such that they fail before the change has been made, then pass once the change has been made.

WRT where the logic lives, ideally it should be in a Presenter-type class or in the Model class.

Thanks.

**Comment by gwensmu** [comment]
@ericcf, right, i am asking a process/priorities question. should i do this
refactoring now, as part of the time i am allocating to this bug fix.

**Comment by ericcf** [comment]
Go ahead and do the refactor now while the code is fresh in your mind!

**Comment by gwensmu** [comment]
@ericcf added a second commit with the changes, thanks for your input!

**Comment by eschlange** [comment]
Looks good.

**Pull request merged**
