### PR TITLE
Revert "Ems 88520746"

### PR DESCRIPTION
**Pull request by michaelwehrley**
Reverts cbitstech/think_feel_do_engine#44

### CODE REVIEW

**Comment by michaelwehrley** [comment]
@eschlange Well, I messed up!  ARG!  I saw you replied, and I wasn't thinking so I merged the original pull request!  So I restored your branch and reverted.  Sorry about this.

**Comment by eschlange** [comment]
@michaelwehrley No problem, Mike. My recent commit adds specs for the new sort logic. I believe it is now ready to be merged for testing.

**Comment by michaelwehrley** [comment]
@eschlange I am not sure what to do here.  This is NOT the pull request we want to merge.  "Reverting" the merged pull request undoes the pull request.  I would DELETE this pull request.

**Comment by michaelwehrley** [comment]
@eschlange I think it might be best to "delete" this pull request and make new pull request of original one.  Then we can delete the last commit on master.  Let me know your thoughts.  Thanks!

**Pull request closed without merging**
